version: "3.8"

services:

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpu-configurator-backend-dec-java
    container_name: gpu-configurator-backend-dec-backend
    restart: on-failure
    ports:
      - "8081:8081"