name: Java CI/CD with Maven

on:
  push:
    branches: [ PresentationLayDev, "maximo/dev" ]
  pull_request:
    branches: [ PresentationLayDev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: |
           mvn clean install -DskipTests
           mkdir artifacts && cp target/*.jar artifacts
           cd artifacts && ls
    - name: Save artifact
      uses: actions/upload-artifact@v2
      with:
        name: github-action-artifact
        path: artifacts
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/gpu-configurator:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull Image from docker hub
        run: sudo docker pull maximomugisha/gpu-configurator:latest
      - name: Delete old container
        run: sudo docker rm -f gpu-configurator
      - name: Run Docker Image
        run: sudo docker run -d -p 8081:8081 --name gpu-configurator maximomugisha/gpu-configurator:latest